In [1]:
#Q1
import numpy as np

# Q1:
arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)

# a)
arr_add = arr + 2
print("After adding 2:", arr_add)

# b)
arr_mul = arr * 3
print("After multiplying by 3:", arr_mul)

# c)
arr_div = arr / 2
print("After dividing by 2:", arr_div)

Original Array: [1 2 3 4 5]
After adding 2: [3 4 5 6 7]
After multiplying by 3: [ 3  6  9 12 15]
After dividing by 2: [0.5 1.  1.5 2.  2.5]


In [2]:
# Q2:
# a)
arr2 = np.array([1, 2, 3, 6, 4, 5])
arr_rev = arr2[::-1]
print("Reversed Array:", arr_rev)

# b)
def most_frequent(arr):
    vals, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_frequent_value = vals[np.argmax(counts)]
    indices = np.where(arr == most_frequent_value)[0]
    return most_frequent_value, indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

x_value, x_indices = most_frequent(x)
y_value, y_indices = most_frequent(y)

print(f"Most frequent value in x: {x_value}, Indices: {x_indices}")
print(f"Most frequent value in y: {y_value}, Indices: {y_indices}")

Reversed Array: [5 4 6 3 2 1]
Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


In [3]:
# Q3:
a_arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Element at (1st row, 2nd column):", a_arr[0, 1])
print("Element at (3rd row, 1st column):", a_arr[2, 0])

Element at (1st row, 2nd column): 20
Element at (3rd row, 1st column): 70


In [5]:
# Q4:
Sahil = np.linspace(10, 100, 25)
print("Array:", Sahil)
print("Dimensions:", Sahil.ndim)
print("Shape:", Sahil.shape)
print("Total elements:", Sahil.size)
print("Data type:", Sahil.dtype)
print("Total bytes consumed:", Sahil.nbytes)

# Transpose
transposed_array = Sahil.reshape(25, 1)
print("Transposed Array using reshape():\n", transposed_array)

# Using T attribute
print("Transpose using T attribute:", Sahil.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200
Transposed Array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [6]:
# Q5:
Sahil = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Mean:", np.mean(Sahil))
print("Median:", np.median(Sahil))
print("Max:", np.max(Sahil))
print("Min:", np.min(Sahil))
print("Unique Elements:", np.unique(Sahil))

# Reshape to 4x3
reshaped_Sahil = Sahil.reshape(4, 3)
print("Reshaped Array (4x3):\n", reshaped_Sahil)

# Resize to 2x3
resized_Sahil = np.resize(Sahil, (2, 3))
print("Resized Array (2x3):\n", resized_Sahil)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
